### PR TITLE
Compatibility with ForgeEssentials

### PR DESCRIPTION
**Pull request by goreacraft**
Loads before FE but after WE

### CODE REVIEW

**Comment by AfterWind** [comment]
The values in the Config.java file are actually the default ones, I would like you to change them back.

**Comment by goreacraft** [comment]
Hello,

Sorry, i didnt know i can change the main project by doing that pull, i am
new with github, i thought it ill be up to the repository owner to accept
after

I will try and see how can i undo all

(Esti cumva roman?)

**Comment by goreacraft** [comment]
sorry but how can i change them back? i new to github

**Comment by AfterWind** [comment]
Da, sunt roman. :D
Doar schimba in cod la tine si dai commit pe fork-ul tau, se va updata automat pull request-ul.

**Comment by goreacraft** [comment]
I made the change back

**Comment by goreacraft** [comment]
Felicitari pentru proiectul MyTown,

Daca ai nevoie de ajutor sa imi spui .. nu sunt profesionist dar invat
repede ;)

As dori sa discutam putin daca ai timp in legatura cu mytown si motivul
pentru care a trebuit sa renunt pentru moment in a-l folosi pe serverele
mele,

Eu sunt pe teamspeak la ip: goreacraft.com

O zi frumoasa,

**Pull request merged**
