### PR TITLE
Update MyTownUniverse.java

### PR DESCRIPTION
**Pull request by blasterdude9**
redo the whole file lets see if it compiles

### CODE REVIEW

**Comment by AfterWind** [comment]
Why are you changing the format of the file?
While I do want a fully consistent format for all the files this is not at all the format that we want for the projects. Leave this to us and don't change it. The issues I find with this format are: variables should never be on the bottom of the file, brackets should not be on an empty new line since it just looks like a waste of space.
What is with the do while loop instead of the for loop? Is there a reason for that to be changed?

**Comment by blasterdude9** [comment]
well one when u redone the file u missed some stuff and what i saw was a public class not working the way it needs to thats y i changed it

**Comment by blasterdude9** [comment]
ok here i show u a screen shot ok

**Comment by blasterdude9** [comment]
public class MyTownUniverse { // TODO Allow migrating between different Datasources

    public static final MyTownUniverse instance = new MyTownUniverse();

    public final ResidentsContainer residents = new ResidentsContainer();
    public final TownsContainer towns = new TownsContainer();
    //public final Map<String, Nation> nations = new HashMap<String, Nation>();
    public final TownBlocksContainer blocks = new TownBlocksContainer();
    public final PlotsContainer plots = new PlotsContainer();
    public final RanksContainer ranks = new RanksContainer();
    public final BanksContainer banks = new BanksContainer();
    public final List<Integer> worlds = new ArrayList<Integer>();

    public MyTownUniverse() {

    } this whole thing is way messed up

**Comment by blasterdude9** [comment]
public class MyTownUniverse { // TODO Allow migrating between different Datasources

{
    public static final MyTownUniverse instance = new MyTownUniverse();

    public final ResidentsContainer residents = new ResidentsContainer();
    public final TownsContainer towns = new TownsContainer();
    //public final Map<String, Nation> nations = new HashMap<String, Nation>();
    public final TownBlocksContainer blocks = new TownBlocksContainer();
    public final PlotsContainer plots = new PlotsContainer();
    public final RanksContainer ranks = new RanksContainer();
    public final BanksContainer banks = new BanksContainer();
    public final List<Integer> worlds = new ArrayList<Integer>();
}

    public MyTownUniverse() {

    }
is what it needs to look like so it know what to do

**Comment by dariusc93** [comment]
It compiles on my workstation as it is on github. Also jenkins compiles it just fine as well as travis. Again, please do not make unnecessary changes or PR.

**Pull request closed without merging**
